### ISSUE TITLE
BaiduPCS-Py安装失败。

### ISSUE THREAD

**Issue by lxmicode** [yaronzz/BaiduYunToAliYun#23]
pip3 install BaiduPCS-Py
Collecting BaiduPCS-Py
  Using cached BaiduPCS-Py-0.6.29.tar.gz (110 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Pillow<9.0.0,>=8.1.2
  Using cached Pillow-8.4.0-cp39-cp39-win_amd64.whl (3.2 MB)
Collecting uvicorn<0.14.0,>=0.13.4
  Using cached uvicorn-0.13.4-py3-none-any.whl (46 kB)
Collecting rich<10.0.0,>=9.12.4
  Using cached rich-9.13.0-py3-none-any.whl (197 kB)
Collecting chardet<5.0.0,>=4.0.0
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting filelock<4.0.0,>=3.0.12
  Using cached filelock-3.3.2-py3-none-any.whl (9.7 kB)
Collecting typing-extensions<4.0.0,>=3.7.4
  Using cached typing_extensions-3.10.0.2-py3-none-any.whl (26 kB)
Collecting requests-toolbelt<0.10.0,>=0.9.1
  Using cached requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
Collecting cryptography<4.0.0,>=3.4.6
  Using cached cryptography-3.4.8-cp36-abi3-win_amd64.whl (1.6 MB)
Collecting requests<3.0.0,>=2.25.1
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting Cython<0.30.0,>=0.29.22
  Using cached Cython-0.29.24-cp39-cp39-win_amd64.whl (1.7 MB)
Collecting Jinja2<3.0.0,>=2.11.3
  Using cached Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Collecting fastapi<0.64.0,>=0.63.0
  Using cached fastapi-0.63.0-py3-none-any.whl (50 kB)
Collecting passlib<2.0.0,>=1.7.4
  Using cached passlib-1.7.4-py2.py3-none-any.whl (525 kB)
Collecting click<8.0.0,>=7.1.2
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting aget<0.2.0,>=0.1.17
  Using cached aget-0.1.17.tar.gz (7.7 kB)
  Preparing metadata (setup.py) ... done
Collecting mugen
  Using cached mugen-0.6.0-py3-none-any.whl
Collecting cffi>=1.12
  Using cached cffi-1.15.0-cp39-cp39-win_amd64.whl (180 kB)
Collecting pydantic<2.0.0,>=1.0.0
  Using cached pydantic-1.8.2-cp39-cp39-win_amd64.whl (1.9 MB)
Collecting starlette==0.13.6
  Using cached starlette-0.13.6-py3-none-any.whl (59 kB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-2.0.1-cp39-cp39-win_amd64.whl (14 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.7-py3-none-any.whl (38 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\users\lu\appdata\local\programs\python\python39\lib\site-packages (from requests<3.0.0,>=2.25.1->BaiduPCS-Py) (1.25.11)
Collecting pygments<3.0.0,>=2.6.0
  Using cached Pygments-2.10.0-py3-none-any.whl (1.0 MB)
Collecting commonmark<0.10.0,>=0.9.0
  Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Collecting colorama<0.5.0,>=0.4.0
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting h11>=0.8
  Using cached h11-0.12.0-py3-none-any.whl (54 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting httptools<0.3.0,>=0.2.0
  Using cached httptools-0.2.0-cp39-cp39-win_amd64.whl (141 kB)
Using legacy 'setup.py install' for aget, since package 'wheel' is not installed.
Building wheels for collected packages: BaiduPCS-Py
  Building wheel for BaiduPCS-Py (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\Users\lu\AppData\Local\Programs\Python\Python39\python.exe' 'D:\Users\lu\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\lu\AppData\Local\Temp\tmpc0dbkj3d'
       cwd: C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be
  Complete output (90 lines):
  信息: 用提供的模式无法找到文件。
  A setup.py file already exists. Using it.
  Compiling baidupcs_py/common/simple_cipher.pyx because it changed.
  [1/1] Cythonizing baidupcs_py/common/simple_cipher.pyx
  running build
  running build_py
  creating C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build
  creating C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9
  creating C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py
  copying baidupcs_py\utils.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py
  copying baidupcs_py\__init__.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py
  creating C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\app
  copying baidupcs_py\app\account.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\app
  copying baidupcs_py\app\app.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\app
  copying baidupcs_py\app\__init__.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\app
  creating C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\baidupcs
  copying baidupcs_py\baidupcs\api.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\baidupcs
  copying baidupcs_py\baidupcs\errors.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\baidupcs
  copying baidupcs_py\baidupcs\inner.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\baidupcs
  copying baidupcs_py\baidupcs\pcs.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\baidupcs
  copying baidupcs_py\baidupcs\phone.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\baidupcs
  copying baidupcs_py\baidupcs\__init__.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\baidupcs
  creating C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\commands
  copying baidupcs_py\commands\cat.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\commands
  copying baidupcs_py\commands\cloud.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\commands
  copying baidupcs_py\commands\crypto.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\commands
  copying baidupcs_py\commands\display.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\commands
  copying baidupcs_py\commands\download.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\commands
  copying baidupcs_py\commands\env.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\commands
  copying baidupcs_py\commands\errors.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\commands
  copying baidupcs_py\commands\file_operators.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\commands
  copying baidupcs_py\commands\list_files.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\commands
  copying baidupcs_py\commands\log.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\commands
  copying baidupcs_py\commands\play.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\commands
  copying baidupcs_py\commands\rapid_upload.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\commands
  copying baidupcs_py\commands\search.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\commands
  copying baidupcs_py\commands\server.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\commands
  copying baidupcs_py\commands\share.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\commands
  copying baidupcs_py\commands\sifter.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\commands
  copying baidupcs_py\commands\sync.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\commands
  copying baidupcs_py\commands\upload.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\commands
  copying baidupcs_py\commands\user.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\commands
  copying baidupcs_py\commands\__init__.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\commands
  package init file 'baidupcs_py\common\__init__.py' not found (or not a regular file)
  creating C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\common
  copying baidupcs_py\common\cache.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\common
  copying baidupcs_py\common\concurrent.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\common
  copying baidupcs_py\common\constant.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\common
  copying baidupcs_py\common\crypto.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\common
  copying baidupcs_py\common\date.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\common
  copying baidupcs_py\common\downloader.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\common
  copying baidupcs_py\common\event.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\common
  copying baidupcs_py\common\file_type.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\common
  copying baidupcs_py\common\io.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\common
  copying baidupcs_py\common\keyboard.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\common
  copying baidupcs_py\common\localstorage.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\common
  copying baidupcs_py\common\log.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\common
  copying baidupcs_py\common\net.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\common
  copying baidupcs_py\common\number.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\common
  copying baidupcs_py\common\path.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\common
  copying baidupcs_py\common\platform.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\common
  copying baidupcs_py\common\progress_bar.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\common
  copying baidupcs_py\common\random.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\common
  copying baidupcs_py\common\url.py -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\common
  copying baidupcs_py\commands\index.html -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\commands
  copying baidupcs_py\common\simple_cipher.c -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\common
  copying baidupcs_py\common\simple_cipher.pyx -> C:\Users\lu\AppData\Local\Temp\pip-install-5y0ybsz6\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\build\lib.win-amd64-3.9\baidupcs_py\common
  running build_ext
  building 'baidupcs_py.common.simple_cipher' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  Traceback (most recent call last):
    File "D:\Users\lu\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
      main()
    File "D:\Users\lu\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "D:\Users\lu\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 261, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "C:\Users\lu\AppData\Local\Temp\pip-build-env-1460i18x\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 68, in build_wheel
      return unicode(WheelBuilder.make_in(poetry, Path(wheel_directory)))
    File "C:\Users\lu\AppData\Local\Temp\pip-build-env-1460i18x\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 72, in make_in
      wb.build()
    File "C:\Users\lu\AppData\Local\Temp\pip-build-env-1460i18x\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 103, in build
      self._build(zip_file)
    File "C:\Users\lu\AppData\Local\Temp\pip-build-env-1460i18x\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 135, in _build
      self._run_build_command(setup)
    File "C:\Users\lu\AppData\Local\Temp\pip-build-env-1460i18x\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 163, in _run_build_command
      subprocess.check_call(
    File "D:\Users\lu\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['D:/Users/lu/AppData/Local/Programs/Python/Python39/python.exe', 'C:\\Users\\lu\\AppData\\Local\\Temp\\pip-install-5y0ybsz6\\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\\setup.py', 'build', '-b', 'C:\\Users\\lu\\AppData\\Local\\Temp\\pip-install-5y0ybsz6\\baidupcs-py_04e0b20652ed442cb4f4de51f42f19be\\build']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for BaiduPCS-Py
Failed to build BaiduPCS-Py
ERROR: Could not build wheels for BaiduPCS-Py, which is required to install pyproject.toml-based projects

**Comment by Baytars** [comment]
#28
