### ISSUE TITLE
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by waahah** [yaronzz/BaiduYunToAliYun#44]
Info: [1] 迁移文件: /我的资源/ROM/Nova9Pro/RNA-AL00 103.0.0.163(C00E160R2P8)_Product Combination Software_HarmonyOS 3.0.0_05017TBD.zip
Traceback (most recent call last):
  File "b2a\__init__.py", line 272, in <module>
  File "b2a\__init__.py", line 262, in main
  File "b2a\__init__.py", line 92, in asyncPath
  File "b2a\trans.py", line 99, in start
  File "b2a\trans.py", line 88, in __movePath__
  File "b2a\trans.py", line 85, in __movePath__
  File "b2a\trans.py", line 61, in moveFile
  File "b2a\bdyplat.py", line 146, in downloadFile
  File "subprocess.py", line 505, in run
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
[7248] Failed to execute script '__init__' due to unhandled exception!

**Comment by allen-wxd** [comment]
请问解决了吗
